### ISSUE TITLE
XCode reports project file version issue

### ISSUE THREAD

**Issue by RichCini** [Moonif/MacBox#18]
I'm trying to compile the March/latest version using XCode 14.2 (14C18) and it's reporting the following error in a system dialog box upon opening the xcodeproj file: "The project at ‘/XCode/MacBox-mainMar/MacBox.xcodeproj’ cannot be opened because it is in a future Xcode project file format. Adjust the project format using a compatible version of Xcode to allow it to be opened by this version of Xcode."

I just tried to open/recompile the version of MacBox from January (1/9/24) and it did not report this error. Any idea what might be causing this?

Thanks!
Rich

**Comment by Moonif** [comment]
Hello!

I think that means that you need to update Xcode to a newer version, as sometimes Apple makes particular changes that older versions of Xcode won't be able to handle it correctly.
MacBox uses the new localization system that was added in Xcode 15 (I added that in February), so that's probably be the cause of the error.

**Comment by RichCini** [comment]
XCode 15 requires MacOS 14 which, for the iMac, only runs on models from 2019 and later. My iMac predates 2019 and will not run OS14 or XCode 15. So, I'm stuck.

Thanks.

**Comment by Moonif** [comment]
I haven't tried it my self, but you could give this a try: [OpenCore Legacy](https://dortania.github.io/OpenCore-Legacy-Patcher/START.html#how-do-i-get-started), it lets you install newer versions of MacOS on older devices.

Good luck!
